CREATE TABLE category(
    id INT PRIMARY KEY NOT NULL,
    category_group_id INT NOT NULL
);

CREATE TABLE category_group(
    id INT PRIMARY KEY NOT NULL,
    name VARCHAR(128)
);

CREATE TABLE mand_category(
    age INT NOT NULL,
    gender CHAR NOT NULL,
    category_id INT NOT NULL,
    gold DOUBLE NOT NULL,
    silver DOUBLE NOT NULL,
    bronze DOUBLE NOT NULL
);
INSERT INTO category(id, category_group_id) VALUES (1,2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',1,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',1,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',1,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',1,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',1,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',1,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',1,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',1,8.5,9.6,10.6);
INSERT INTO category(id, category_group_id) VALUES (2,4);
INSERT INTO category(id, category_group_id) VALUES (3,4);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',3,14.1,15.4,17);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'m',3,14.1,15.4,17);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'m',3,13.5,14.8,16.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'m',3,13.5,14.8,16.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (18,'m',3,13.2,14.6,16);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (19,'m',3,13.2,14.6,16);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (20,'m',3,13,14.4,15.8);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',3,15.5,17,18.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'w',3,15.5,17,18.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'w',3,15,16.3,17.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'w',3,15,16.3,17.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (18,'w',3,15.3,16.5,18.2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (19,'w',3,15.3,16.5,18.2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (20,'w',3,15.6,16.8,18.5);
INSERT INTO category(id, category_group_id) VALUES (4,3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'m',4,3.2,2.9,2.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',4,3.2,2.9,2.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',4,3.8,3.5,3.2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',4,3.8,3.5,3.2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',4,4.4,4.1,3.8);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'m',4,4.4,4.1,3.8);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'m',4,4.9,4.6,4.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'m',4,4.9,4.6,4.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (18,'m',4,5.1,4.8,4.5);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (19,'m',4,5.1,4.8,4.5);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (20,'m',4,5,4.7,4.4);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'w',4,2.9,2.6,2.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',4,2.9,2.6,2.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',4,3.4,3.1,2.8);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',4,3.4,3.1,2.8);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',4,3.8,3.5,3.2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'w',4,3.8,3.5,3.2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'w',4,4,3.7,3.4);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'w',4,4,3.7,3.4);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (18,'w',4,4,3.7,3.4);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (19,'w',4,4,3.7,3.4);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (20,'w',4,4,3.7,3.4);
INSERT INTO category(id, category_group_id) VALUES (5,1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',5,33,30,26);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',5,33,30,26);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',5,37,34,30);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'m',5,37,34,30);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'m',5,42,38,34);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'m',5,42,38,34);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',5,27,24,20);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'w',5,27,24,20);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'w',5,31,27,24);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'w',5,31,27,24);
INSERT INTO category(id, category_group_id) VALUES (6,1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'m',6,1.85,1.7,1.5);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',6,1.85,1.7,1.5);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',6,2.05,1.9,1.7);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',6,2.05,1.9,1.7);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',6,2.25,2.05,1.9);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'m',6,2.25,2.05,1.9);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'m',6,2.4,2.2,2.05);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'m',6,2.4,2.2,2.05);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (18,'m',6,2.5,2.3,2.1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (19,'m',6,2.5,2.3,2.1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (20,'m',6,2.5,2.3,2.1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'w',6,1.65,1.45,1.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',6,1.65,1.45,1.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',6,1.8,1.6,1.4);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',6,1.8,1.6,1.4);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',6,1.9,1.7,1.55);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'w',6,1.9,1.7,1.55);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'w',6,2,1.8,1.65);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'w',6,2,1.8,1.65);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (18,'w',6,2.05,1.85,1.65);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (19,'w',6,2.05,1.85,1.65);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (20,'w',6,2,1.8,1.6);
INSERT INTO category(id, category_group_id) VALUES (7,2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'m',7,215,260,305);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',7,215,260,305);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',7,195,240,285);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',7,195,240,285);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',7,180,220,260);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'m',7,180,220,260);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'m',7,165,205,245);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'m',7,165,205,245);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'w',7,240,280,320);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',7,240,280,320);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',7,225,265,310);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',7,225,265,310);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',7,215,260,300);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'w',7,215,260,300);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'w',7,205,245,290);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'w',7,205,245,290);
INSERT INTO category(id, category_group_id) VALUES (8,4);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'m',8,8.4,9.3,10.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',8,8.4,9.3,10.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',8,8.1,8.9,9.7);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',8,8.1,8.9,9.7);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'w',8,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',8,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',8,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',8,8.5,9.6,10.6);
INSERT INTO category(id, category_group_id) VALUES (9,3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'m',9,1.05,0.95,0.85);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',9,1.05,0.95,0.85);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',9,1.15,1.05,0.95);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',9,1.15,1.05,0.95);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',9,1.3,1.2,1.1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'m',9,1.3,1.2,1.1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'m',9,1.4,1.3,1.2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'m',9,1.4,1.3,1.2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (18,'m',9,1.5,1.4,1.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (19,'m',9,1.5,1.4,1.3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (20,'m',9,1.55,1.45,1.35);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'w',9,1,0.9,0.8);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',9,1,0.9,0.8);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',9,1.1,1,0.9);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',9,1.1,1,0.9);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',9,1.15,1.05,0.95);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'w',9,1.15,1.05,0.95);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'w',9,1.25,1.15,1.05);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'w',9,1.25,1.15,1.05);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (18,'w',9,1.3,1.2,1.1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (19,'w',9,1.3,1.2,1.1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (20,'w',9,1.3,1.2,1.1);
INSERT INTO category(id, category_group_id) VALUES (10,2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',10,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',10,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',10,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',10,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',10,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',10,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',10,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',10,8.5,9.6,10.6);
INSERT INTO category(id, category_group_id) VALUES (11,1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'m',11,28,25,21);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',11,28,25,21);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (10,'w',11,18,15,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',11,18,15,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',11,22,18,15);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',11,22,18,15);
INSERT INTO category(id, category_group_id) VALUES (12,1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',12,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',12,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',12,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',12,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',12,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',12,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',12,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',12,8.5,9.6,10.6);
INSERT INTO category(id, category_group_id) VALUES (13,3);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',13,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',13,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',13,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',13,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',13,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',13,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',13,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',13,8.5,9.6,10.6);
INSERT INTO category(id, category_group_id) VALUES (14,1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',14,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',14,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',14,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',14,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',14,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',14,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',14,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',14,8.5,9.6,10.6);
INSERT INTO category(id, category_group_id) VALUES (15,1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',15,7.25,6.75,6.25);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',15,7.25,6.75,6.25);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',15,5.75,5.25,4.75);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',15,5.75,5.25,4.75);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',15,6.5,6,5.5);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'w',15,6.5,6,5.5);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (16,'w',15,6.75,6.25,5.75);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (17,'w',15,6.75,6.25,5.75);
INSERT INTO category(id, category_group_id) VALUES (16,2);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',16,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',16,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',16,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',16,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',16,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',16,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',16,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',16,8.5,9.6,10.6);
INSERT INTO category(id, category_group_id) VALUES (17,1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'m',17,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'m',17,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'m',17,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',17,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (11,'w',17,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (12,'w',17,9.1,10.1,11);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (13,'w',17,8.5,9.6,10.6);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'w',17,8.5,9.6,10.6);
INSERT INTO category(id, category_group_id) VALUES (18,1);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (14,'m',18,8,7.5,7);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (15,'m',18,8,7.5,7);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (18,'w',18,7.5,7,6.5);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (19,'w',18,7.5,7,6.5);
INSERT INTO mand_category(age, gender, category_id, gold, silver, bronze) VALUES (20,'w',18,7.5,7,6.5);
